import styled from "styled-components";

export const all = styled.body`
background:red;
`

export const ServicesCard = styled.div`
    background-color: #000;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    position: relative;
    align-items: center;
    border-radius: 10px;
    max-height: 340px;
    padding: 20px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.2);
    transition: all 1s ease-in-out;
    overflow: hidden;
    animation:shadow-drop-2-br 1s cubic-bezier(.25,.46,.45,.94) both;
   /* ----------------------------------------------
 * Generated by Animista on 2021-6-24 18:59:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes shadow-drop-2-br{0%{transform:translateZ(0) translateX(0) translateY(0);box-shadow:0 0 0 0 transparent}100%{transform:translateZ(50px) translateX(-12px) translateY(-12px);box-shadow:12px 12px 20px -12px rgba(180,190,190,.35)}}

 
    &:hover{
        transition: all 0.2s ease-in-out;
        cursor: pointer;
    }
    &:hover img{
        transform: scale(1.2);
        transition: all 0.5s ease-in-out;
    }
`

export const ServicesIcon = styled.img`
height: 200px;
width: 260px;
margin-bottom: 10px;
opacity: ${({enter})=>(enter ? '0.1': '1')};
transition: all 0.5s ease-in-out;
`


export const ServicesH2 = styled.h2`
color: #fff;
    font-size: 1rem;
    margin-bottom: 10px;
    opacity: ${({enter})=>(enter ? '0.1': '1')};
    transition: all 0.5s ease-in-out;
`
export const ServicesP = styled.p`
color: #fff;
    font-size: 1rem;
    text-align: center;
    opacity: ${({enter})=>(enter ? '0.1': '1')};
    transition: all 0.5s ease-in-out;
`
export const Coverpage = styled.div`
    position: absolute;
    top:0;
    left:0;
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    font-size: 18px;
    font-weight: bold;
    line-height: 24px;
    border-radius: 30px;
    animation:flip-vertical-fwd 0.5s cubic-bezier(.645,.045,.355,1.000) .3s both, tracking-in-contract-bck-top 1s cubic-bezier(.215,.61,.355,1.000) both;; 

    /* ----------------------------------------------
 * Generated by Animista on 2021-6-24 18:24:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes flip-vertical-fwd{0%{transform:translateZ(0) rotateY(-180deg) rotateX(-180deg)}100%{transform:translateZ(160px) rotateX(0)rotateY(0) scale(1.0); background:#04BF71;}}
/* ----------------------------------------------
 * Generated by Animista on 2021-6-24 19:4:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes tracking-in-contract-bck-top{0%{letter-spacing:1em;transform:translateZ(400px) translateY(-300px);opacity:0}40%{opacity:.6}100%{transform:translateZ(0) translateY(0);opacity:1}}
    
`